###################################################################

# Created by write_sdc on Sun Apr 26 11:08:50 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_max_area 0
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports reset]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports zeroize]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports tamper_in]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports key_wr_en]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {key_wr_addr[2]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {key_wr_addr[1]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {key_wr_addr[0]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {key_wr_data[31]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {key_wr_data[30]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {key_wr_data[29]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {key_wr_data[28]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {key_wr_data[27]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {key_wr_data[26]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {key_wr_data[25]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {key_wr_data[24]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {key_wr_data[23]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {key_wr_data[22]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {key_wr_data[21]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {key_wr_data[20]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {key_wr_data[19]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {key_wr_data[18]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {key_wr_data[17]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {key_wr_data[16]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {key_wr_data[15]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {key_wr_data[14]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {key_wr_data[13]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {key_wr_data[12]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {key_wr_data[11]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {key_wr_data[10]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {key_wr_data[9]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {key_wr_data[8]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {key_wr_data[7]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {key_wr_data[6]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {key_wr_data[5]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {key_wr_data[4]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {key_wr_data[3]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {key_wr_data[2]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {key_wr_data[1]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {key_wr_data[0]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports commit]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports blk_wr_en]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {blk_wr_addr[1]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {blk_wr_addr[0]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {blk_wr_data[31]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {blk_wr_data[30]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {blk_wr_data[29]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {blk_wr_data[28]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {blk_wr_data[27]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {blk_wr_data[26]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {blk_wr_data[25]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {blk_wr_data[24]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {blk_wr_data[23]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {blk_wr_data[22]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {blk_wr_data[21]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {blk_wr_data[20]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {blk_wr_data[19]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {blk_wr_data[18]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {blk_wr_data[17]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {blk_wr_data[16]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {blk_wr_data[15]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {blk_wr_data[14]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {blk_wr_data[13]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {blk_wr_data[12]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {blk_wr_data[11]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {blk_wr_data[10]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {blk_wr_data[9]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {blk_wr_data[8]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {blk_wr_data[7]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {blk_wr_data[6]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {blk_wr_data[5]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {blk_wr_data[4]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {blk_wr_data[3]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {blk_wr_data[2]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {blk_wr_data[1]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {blk_wr_data[0]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports aes_start]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports rd_en]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {rd_addr[1]}]
set_driving_cell -lib_cell DFFRX1 -pin Q [get_ports {rd_addr[0]}]
set_load -pin_load 0.000207334 [get_ports {rd_data[31]}]
set_load -pin_load 0.000207334 [get_ports {rd_data[30]}]
set_load -pin_load 0.000207334 [get_ports {rd_data[29]}]
set_load -pin_load 0.000207334 [get_ports {rd_data[28]}]
set_load -pin_load 0.000207334 [get_ports {rd_data[27]}]
set_load -pin_load 0.000207334 [get_ports {rd_data[26]}]
set_load -pin_load 0.000207334 [get_ports {rd_data[25]}]
set_load -pin_load 0.000207334 [get_ports {rd_data[24]}]
set_load -pin_load 0.000207334 [get_ports {rd_data[23]}]
set_load -pin_load 0.000207334 [get_ports {rd_data[22]}]
set_load -pin_load 0.000207334 [get_ports {rd_data[21]}]
set_load -pin_load 0.000207334 [get_ports {rd_data[20]}]
set_load -pin_load 0.000207334 [get_ports {rd_data[19]}]
set_load -pin_load 0.000207334 [get_ports {rd_data[18]}]
set_load -pin_load 0.000207334 [get_ports {rd_data[17]}]
set_load -pin_load 0.000207334 [get_ports {rd_data[16]}]
set_load -pin_load 0.000207334 [get_ports {rd_data[15]}]
set_load -pin_load 0.000207334 [get_ports {rd_data[14]}]
set_load -pin_load 0.000207334 [get_ports {rd_data[13]}]
set_load -pin_load 0.000207334 [get_ports {rd_data[12]}]
set_load -pin_load 0.000207334 [get_ports {rd_data[11]}]
set_load -pin_load 0.000207334 [get_ports {rd_data[10]}]
set_load -pin_load 0.000207334 [get_ports {rd_data[9]}]
set_load -pin_load 0.000207334 [get_ports {rd_data[8]}]
set_load -pin_load 0.000207334 [get_ports {rd_data[7]}]
set_load -pin_load 0.000207334 [get_ports {rd_data[6]}]
set_load -pin_load 0.000207334 [get_ports {rd_data[5]}]
set_load -pin_load 0.000207334 [get_ports {rd_data[4]}]
set_load -pin_load 0.000207334 [get_ports {rd_data[3]}]
set_load -pin_load 0.000207334 [get_ports {rd_data[2]}]
set_load -pin_load 0.000207334 [get_ports {rd_data[1]}]
set_load -pin_load 0.000207334 [get_ports {rd_data[0]}]
set_load -pin_load 0.000207334 [get_ports rd_valid]
set_load -pin_load 0.000207334 [get_ports unlocked]
set_load -pin_load 0.000207334 [get_ports trap]
set_load -pin_load 0.000207334 [get_ports aes_enable]
set_load -pin_load 0.000207334 [get_ports auth_zeroize]
set_load -pin_load 0.000207334 [get_ports tamper_latched]
set_load -pin_load 0.000207334 [get_ports result_ready]
set_load -pin_load 0.000207334 [get_ports {key_sel[1]}]
set_load -pin_load 0.000207334 [get_ports {key_sel[0]}]
set_load -pin_load 0.000207334 [get_ports {state_debug[1]}]
set_load -pin_load 0.000207334 [get_ports {state_debug[0]}]
create_clock [get_ports clk]  -period 10  -waveform {0 5}
set_clock_uncertainty 0.05  [get_clocks clk]
set_input_delay -clock clk  0.1  [get_ports reset]
set_input_delay -clock clk  0.1  [get_ports zeroize]
set_input_delay -clock clk  0.1  [get_ports tamper_in]
set_input_delay -clock clk  0.1  [get_ports key_wr_en]
set_input_delay -clock clk  0.1  [get_ports {key_wr_addr[2]}]
set_input_delay -clock clk  0.1  [get_ports {key_wr_addr[1]}]
set_input_delay -clock clk  0.1  [get_ports {key_wr_addr[0]}]
set_input_delay -clock clk  0.1  [get_ports {key_wr_data[31]}]
set_input_delay -clock clk  0.1  [get_ports {key_wr_data[30]}]
set_input_delay -clock clk  0.1  [get_ports {key_wr_data[29]}]
set_input_delay -clock clk  0.1  [get_ports {key_wr_data[28]}]
set_input_delay -clock clk  0.1  [get_ports {key_wr_data[27]}]
set_input_delay -clock clk  0.1  [get_ports {key_wr_data[26]}]
set_input_delay -clock clk  0.1  [get_ports {key_wr_data[25]}]
set_input_delay -clock clk  0.1  [get_ports {key_wr_data[24]}]
set_input_delay -clock clk  0.1  [get_ports {key_wr_data[23]}]
set_input_delay -clock clk  0.1  [get_ports {key_wr_data[22]}]
set_input_delay -clock clk  0.1  [get_ports {key_wr_data[21]}]
set_input_delay -clock clk  0.1  [get_ports {key_wr_data[20]}]
set_input_delay -clock clk  0.1  [get_ports {key_wr_data[19]}]
set_input_delay -clock clk  0.1  [get_ports {key_wr_data[18]}]
set_input_delay -clock clk  0.1  [get_ports {key_wr_data[17]}]
set_input_delay -clock clk  0.1  [get_ports {key_wr_data[16]}]
set_input_delay -clock clk  0.1  [get_ports {key_wr_data[15]}]
set_input_delay -clock clk  0.1  [get_ports {key_wr_data[14]}]
set_input_delay -clock clk  0.1  [get_ports {key_wr_data[13]}]
set_input_delay -clock clk  0.1  [get_ports {key_wr_data[12]}]
set_input_delay -clock clk  0.1  [get_ports {key_wr_data[11]}]
set_input_delay -clock clk  0.1  [get_ports {key_wr_data[10]}]
set_input_delay -clock clk  0.1  [get_ports {key_wr_data[9]}]
set_input_delay -clock clk  0.1  [get_ports {key_wr_data[8]}]
set_input_delay -clock clk  0.1  [get_ports {key_wr_data[7]}]
set_input_delay -clock clk  0.1  [get_ports {key_wr_data[6]}]
set_input_delay -clock clk  0.1  [get_ports {key_wr_data[5]}]
set_input_delay -clock clk  0.1  [get_ports {key_wr_data[4]}]
set_input_delay -clock clk  0.1  [get_ports {key_wr_data[3]}]
set_input_delay -clock clk  0.1  [get_ports {key_wr_data[2]}]
set_input_delay -clock clk  0.1  [get_ports {key_wr_data[1]}]
set_input_delay -clock clk  0.1  [get_ports {key_wr_data[0]}]
set_input_delay -clock clk  0.1  [get_ports commit]
set_input_delay -clock clk  0.1  [get_ports blk_wr_en]
set_input_delay -clock clk  0.1  [get_ports {blk_wr_addr[1]}]
set_input_delay -clock clk  0.1  [get_ports {blk_wr_addr[0]}]
set_input_delay -clock clk  0.1  [get_ports {blk_wr_data[31]}]
set_input_delay -clock clk  0.1  [get_ports {blk_wr_data[30]}]
set_input_delay -clock clk  0.1  [get_ports {blk_wr_data[29]}]
set_input_delay -clock clk  0.1  [get_ports {blk_wr_data[28]}]
set_input_delay -clock clk  0.1  [get_ports {blk_wr_data[27]}]
set_input_delay -clock clk  0.1  [get_ports {blk_wr_data[26]}]
set_input_delay -clock clk  0.1  [get_ports {blk_wr_data[25]}]
set_input_delay -clock clk  0.1  [get_ports {blk_wr_data[24]}]
set_input_delay -clock clk  0.1  [get_ports {blk_wr_data[23]}]
set_input_delay -clock clk  0.1  [get_ports {blk_wr_data[22]}]
set_input_delay -clock clk  0.1  [get_ports {blk_wr_data[21]}]
set_input_delay -clock clk  0.1  [get_ports {blk_wr_data[20]}]
set_input_delay -clock clk  0.1  [get_ports {blk_wr_data[19]}]
set_input_delay -clock clk  0.1  [get_ports {blk_wr_data[18]}]
set_input_delay -clock clk  0.1  [get_ports {blk_wr_data[17]}]
set_input_delay -clock clk  0.1  [get_ports {blk_wr_data[16]}]
set_input_delay -clock clk  0.1  [get_ports {blk_wr_data[15]}]
set_input_delay -clock clk  0.1  [get_ports {blk_wr_data[14]}]
set_input_delay -clock clk  0.1  [get_ports {blk_wr_data[13]}]
set_input_delay -clock clk  0.1  [get_ports {blk_wr_data[12]}]
set_input_delay -clock clk  0.1  [get_ports {blk_wr_data[11]}]
set_input_delay -clock clk  0.1  [get_ports {blk_wr_data[10]}]
set_input_delay -clock clk  0.1  [get_ports {blk_wr_data[9]}]
set_input_delay -clock clk  0.1  [get_ports {blk_wr_data[8]}]
set_input_delay -clock clk  0.1  [get_ports {blk_wr_data[7]}]
set_input_delay -clock clk  0.1  [get_ports {blk_wr_data[6]}]
set_input_delay -clock clk  0.1  [get_ports {blk_wr_data[5]}]
set_input_delay -clock clk  0.1  [get_ports {blk_wr_data[4]}]
set_input_delay -clock clk  0.1  [get_ports {blk_wr_data[3]}]
set_input_delay -clock clk  0.1  [get_ports {blk_wr_data[2]}]
set_input_delay -clock clk  0.1  [get_ports {blk_wr_data[1]}]
set_input_delay -clock clk  0.1  [get_ports {blk_wr_data[0]}]
set_input_delay -clock clk  0.1  [get_ports aes_start]
set_input_delay -clock clk  0.1  [get_ports rd_en]
set_input_delay -clock clk  0.1  [get_ports {rd_addr[1]}]
set_input_delay -clock clk  0.1  [get_ports {rd_addr[0]}]
set_output_delay -clock clk  0.4  [get_ports {rd_data[31]}]
set_output_delay -clock clk  0.4  [get_ports {rd_data[30]}]
set_output_delay -clock clk  0.4  [get_ports {rd_data[29]}]
set_output_delay -clock clk  0.4  [get_ports {rd_data[28]}]
set_output_delay -clock clk  0.4  [get_ports {rd_data[27]}]
set_output_delay -clock clk  0.4  [get_ports {rd_data[26]}]
set_output_delay -clock clk  0.4  [get_ports {rd_data[25]}]
set_output_delay -clock clk  0.4  [get_ports {rd_data[24]}]
set_output_delay -clock clk  0.4  [get_ports {rd_data[23]}]
set_output_delay -clock clk  0.4  [get_ports {rd_data[22]}]
set_output_delay -clock clk  0.4  [get_ports {rd_data[21]}]
set_output_delay -clock clk  0.4  [get_ports {rd_data[20]}]
set_output_delay -clock clk  0.4  [get_ports {rd_data[19]}]
set_output_delay -clock clk  0.4  [get_ports {rd_data[18]}]
set_output_delay -clock clk  0.4  [get_ports {rd_data[17]}]
set_output_delay -clock clk  0.4  [get_ports {rd_data[16]}]
set_output_delay -clock clk  0.4  [get_ports {rd_data[15]}]
set_output_delay -clock clk  0.4  [get_ports {rd_data[14]}]
set_output_delay -clock clk  0.4  [get_ports {rd_data[13]}]
set_output_delay -clock clk  0.4  [get_ports {rd_data[12]}]
set_output_delay -clock clk  0.4  [get_ports {rd_data[11]}]
set_output_delay -clock clk  0.4  [get_ports {rd_data[10]}]
set_output_delay -clock clk  0.4  [get_ports {rd_data[9]}]
set_output_delay -clock clk  0.4  [get_ports {rd_data[8]}]
set_output_delay -clock clk  0.4  [get_ports {rd_data[7]}]
set_output_delay -clock clk  0.4  [get_ports {rd_data[6]}]
set_output_delay -clock clk  0.4  [get_ports {rd_data[5]}]
set_output_delay -clock clk  0.4  [get_ports {rd_data[4]}]
set_output_delay -clock clk  0.4  [get_ports {rd_data[3]}]
set_output_delay -clock clk  0.4  [get_ports {rd_data[2]}]
set_output_delay -clock clk  0.4  [get_ports {rd_data[1]}]
set_output_delay -clock clk  0.4  [get_ports {rd_data[0]}]
set_output_delay -clock clk  0.4  [get_ports rd_valid]
set_output_delay -clock clk  0.4  [get_ports unlocked]
set_output_delay -clock clk  0.4  [get_ports trap]
set_output_delay -clock clk  0.4  [get_ports aes_enable]
set_output_delay -clock clk  0.4  [get_ports auth_zeroize]
set_output_delay -clock clk  0.4  [get_ports tamper_latched]
set_output_delay -clock clk  0.4  [get_ports result_ready]
set_output_delay -clock clk  0.4  [get_ports {key_sel[1]}]
set_output_delay -clock clk  0.4  [get_ports {key_sel[0]}]
set_output_delay -clock clk  0.4  [get_ports {state_debug[1]}]
set_output_delay -clock clk  0.4  [get_ports {state_debug[0]}]
